theme = "cybercore"

draw-bold-text-with-light-colors = true

line-height = 1.18

margin = [14, 18, 10, 18]

scrollback-history-limit = 20000
confirm-before-quit = false
copy-on-select = false
hide-mouse-cursor-when-typing = true


[colors]

cursor = "#00ffff"
vi-cursor = "#00ffff"
selection-background = "#c4d8f2"
selection-foreground = "#00ffff"

[window]
opacity = 0.97
opacity-cells = true
blur = true
decorations = "Enabled"

[fonts]
family = "FiraCode Nerd Font Mono"
size = 12
use-drawable-chars = true
hinting = true
features = ["calt", "liga"]
disable-warnings-not-found = false



symbol-map = [
  { start = "23FB", end = "23FF", "font-family" = "Symbols Nerd Font Mono" },
  { start = "E000", end = "E00B", "font-family" = "Symbols Nerd Font Mono" },
  { start = "E0A0", end = "E0A4", "font-family" = "Symbols Nerd Font Mono" },
  { start = "E0B0", end = "E0D8", "font-family" = "Symbols Nerd Font Mono" },
  { start = "E200", end = "E2AA", "font-family" = "Symbols Nerd Font Mono" },
  { start = "E300", end = "E3E4", "font-family" = "Symbols Nerd Font Mono" },
  { start = "E5FA", end = "E6B8", "font-family" = "Symbols Nerd Font Mono" },
  { start = "E700", end = "E8F0", "font-family" = "Symbols Nerd Font Mono" },
  { start = "EA60", end = "EC1F", "font-family" = "Symbols Nerd Font Mono" },
  { start = "ED00", end = "EFCF", "font-family" = "Symbols Nerd Font Mono" },
  { start = "F300", end = "F382", "font-family" = "Symbols Nerd Font Mono" },
  { start = "F400", end = "F534", "font-family" = "Symbols Nerd Font Mono" },
  { start = "F0001", end = "F1AF1", "font-family" = "Symbols Nerd Font Mono" },
  { start = "21D0", end = "21FF", "font-family" = "DejaVu Sans" },
  { start = "1F300", end = "1FAFF", "font-family" = "Noto Color Emoji" },

  { start = "2600", end = "26A1", "font-family" = "DejaVu Sans" },
  { start = "26A2", end = "276C", "font-family" = "DejaVu Sans" },
  { start = "2772", end = "27C0", "font-family" = "DejaVu Sans" },
]

[cursor]
shape = "block"
blinking = true
blinking-interval = 600

[effects]
trail-cursor = true
custom-mouse-cursor = false
trail-cursor-color = "#00ffff"

[navigation]
mode = "Tab"
hide-if-single = true
use-split = true
current-working-directory = true
unfocused-split-opacity = 0.55
enable-scroll-bar = true


[[navigation.color-automation]]
program = "nvim"
color = "#00F0FF"

[[navigation.color-automation]]
program = "vim"
color = "#00F0FF"

[[navigation.color-automation]]
program = "ssh"
color = "#FF2FD6"

[[navigation.color-automation]]
program = "sudo"
color = "#FF2E6E"

[[navigation.color-automation]]
program = "btop"
color = "#31FFB0"

[panel]
padding = [6]
border-width = 1
border-radius = 6
row-gap = 4
column-gap = 4

[title]
content = "{{ title || program }}"
placeholder = "▮ rio"

[bell]
audio = true

[renderer]
backend = "Webgpu"
filters = ["__RIO_SHADER__/newpixie-crt.slangp"]
strategy = "events"
disable-unfocused-render = false
